### ISSUE TITLE
SOAP-ERROR: Encoding: object has no 'alias' property

### ISSUE THREAD

**Issue by nitaipanda** [eupago/eupago-module-mbway#3]
trace: "#0 /home/websteptechco/pegada27.websteptech.co.uk/app/code/Eupago/MbWay/Gateway/Http/Client/Client.php(67): SoapClient->__soapCall('pedidoMBW', Array)↵#1 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-payment/Gateway/Command/GatewayCommand.php(102): Eupago\MbWay\Gateway\Http\Client\Client->placeRequest(Object(Magento\Payment\Gateway\Http\Transfer))↵#2 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-payment/Model/Method/Adapter.php(546): Magento\Payment\Gateway\Command\GatewayCommand->execute(Array)↵#3 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-payment/Model/Method/Adapter.php(448): Magento\Payment\Model\Method\Adapter->executeCommand('authorize', Array)↵#4 /home/websteptechco/pegada27.websteptech.co.uk/generated/code/Magento/Payment/Model/Method/Adapter/Interceptor.php(349): Magento\Payment\Model\Method\Adapter->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 15.05)↵#5 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Order/Payment/Operations/AuthorizeOperation.php(45): Magento\Payment\Model\Method\Adapter\Interceptor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), 15.05)↵#6 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Order/Payment/Processor.php(72): Magento\Sales\Model\Order\Payment\Operations\AuthorizeOperation->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 15.05)↵#7 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Order/Payment.php(1107): Magento\Sales\Model\Order\Payment\Processor->authorize(Object(Magento\Sales\Model\Order\Payment\Interceptor), true, 15.05)↵#8 /home/websteptechco/pegada27.websteptech.co.uk/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(427): Magento\Sales\Model\Order\Payment->authorize(true, 15.05)↵#9 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Order/Payment.php(441): Magento\Sales\Model\Order\Payment\Interceptor->authorize(true, 15.05)↵#10 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Order/Payment.php(368): Magento\Sales\Model\Order\Payment->processAction('authorize', Object(Magento\Sales\Model\Order\Interceptor))↵#11 /home/websteptechco/pegada27.websteptech.co.uk/generated/code/Magento/Sales/Model/Order/Payment/Interceptor.php(167): Magento\Sales\Model\Order\Payment->place()↵#12 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Order.php(873): Magento\Sales\Model\Order\Payment\Interceptor->place()↵#13 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Order.php(1080): Magento\Sales\Model\Order->_placePayment()↵#14 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Sales\Model\Order->place()↵#15 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Sales\Model\Order\Interceptor->___callParent('place', Array)↵#16 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Sales\Model\Order\Interceptor->Magento\Framework\Interception\{closure}()↵#17 /home/websteptechco/pegada27.websteptech.co.uk/generated/code/Magento/Sales/Model/Order/Interceptor.php(494): Magento\Sales\Model\Order\Interceptor->___callPlugins('place', Array, Array)↵#18 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-sales/Model/Service/OrderService.php(201): Magento\Sales\Model\Order\Interceptor->place()↵#19 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-quote/Model/QuoteManagement.php(513): Magento\Sales\Model\Service\OrderService->place(Object(Magento\Sales\Model\Order\Interceptor))↵#20 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-quote/Model/QuoteManagement.php(406): Magento\Quote\Model\QuoteManagement->submitQuote(Object(Magento\Quote\Model\Quote\Interceptor), Array)↵#21 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-quote/Model/QuoteManagement.php(364): Magento\Quote\Model\QuoteManagement->submit(Object(Magento\Quote\Model\Quote\Interceptor))↵#22 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-checkout/Model/PaymentInformationManagement.php(83): Magento\Quote\Model\QuoteManagement->placeOrder(217331)↵#23 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Checkout\Model\PaymentInformationManagement->savePaymentInformationAndPlaceOrder(217331, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#24 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callParent('savePaymentInfo...', Array)↵#25 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->Magento\Framework\Interception\{closure}(217331, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#26 /home/websteptechco/pegada27.websteptech.co.uk/generated/code/Magento/Checkout/Model/PaymentInformationManagement/Interceptor.php(26): Magento\Checkout\Model\PaymentInformationManagement\Interceptor->___callPlugins('savePaymentInfo...', Array, Array)↵#27 [internal function]: Magento\Checkout\Model\PaymentInformationManagement\Interceptor->savePaymentInformationAndPlaceOrder(217331, Object(Magento\Quote\Model\Quote\Payment\Interceptor), Object(Magento\Quote\Model\Quote\Address\Interceptor))↵#28 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)↵#29 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/module-webapi/Controller/Rest.php(244): Magento\Webapi\Controller\Rest\SynchronousRequestProcessor->process(Object(Magento\Framework\Webapi\Rest\Request\Proxy))↵#30 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Webapi\Controller\Rest->dispatch(Object(Magento\Framework\App\Request\Http))↵#31 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Webapi\Controller\Rest\Interceptor->___callParent('dispatch', Array)↵#32 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Webapi\Controller\Rest\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))↵#33 /home/websteptechco/pegada27.websteptech.co.uk/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(39): Magento\Webapi\Controller\Rest\Interceptor->___callPlugins('dispatch', Array, Array)↵#34 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Rest\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))↵#35 /home/websteptechco/pegada27.websteptech.co.uk/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch()↵#36 /home/websteptechco/pegada27.websteptech.co.uk/vendor/magento/framework/App/Bootstrap.php(257): Magento\Framework\App\Http\Interceptor->launch()↵#37 /home/websteptechco/pegada27.websteptech.co.uk/index.php(58): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))↵#38 {main}

**Comment by nitaipanda** [comment]
how to solve this issues please help me as soon as possible.
